spring:
  application:
    name: t-springboot-java
  profiles:
    active: local

server:
  port: 8080

logging:
  level:
    root: info
    sun.rmi: info
    javax.management: info

management:
  endpoints:
    web:
      exposure:
        include: health, info  # 모든 엔드포인트 노출 = *
  endpoint:
    health:
      show-details: when_authorized  # health 상세 정보 표시 여부
